<?php
define('SETTING_MIN_PLAN_NAME_LENGTH', 2);
define('SETTING_MAX_PLAN_NAME_LENGTH', 35);
define('SETTING_MAX_DESCRIPTION_LENGTH', 2000);
define('SETTING_MAX_EXERCISE_NAME_LENGTH', 25);
define('SETTING_MAX_UNITS_LENGTH', 12);